package se.lnu.prosses.core;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Hashtable;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import org.xmlpull.v1.XmlPullParserException;

import se.lnu.prosses.configs.Configuration;
import se.lnu.prosses.configs.Constants;
import se.lnu.prosses.frontend.JSymCompiler;
import se.lnu.prosses.utils.Utils;
import se.lnu.prosses.utils.XMLSecstubsParser;
import se.lnu.prosses.utils.XMLSourceSinkParser;
import soot.Scene;
import soot.SootClass;
import soot.SootMethod;
import soot.Type;
import soot.Value;

public class ProjectHelper {
    public static ArrayList<String> javaSecstubs = new ArrayList<String>();
    public SourceSinkHelper sourceSinkHelper = new SourceSinkHelper();
    public Hashtable<String, ArrayList<SecuritySignature>> securitySignatures = new Hashtable<String, ArrayList<SecuritySignature>>();
    public Configuration configurations = new Configuration();
    private LinkedHashMap<SootMethod, ArrayList<String>> autoGenLibSecstubs = new LinkedHashMap<SootMethod, ArrayList<String>>();
    public String staticFileds = "";
    public List<SootMethod> methodsWithNoSecSignature = new ArrayList<SootMethod>();
    public List<SootMethod> methodsWithAutoGeneratedSecSignature = new ArrayList<SootMethod>();

    private List<String> errLog = new ArrayList<>();

    public void writeErrLog() {
	Utils.writeTextFile(configurations.targetDir + File.separator + Constants.errLogFile, errLog);
    }

    public void logErr(String err) {
	errLog.add(err);
	Utils.logErr(getClass(), err);
    }

    public class SecuritySignature {
	public String className;
	public String method;
	public String returnType;
	public String[] argsType = new String[] {};
	public List<String> secSignature = new ArrayList<String>();
	public boolean isStatic = false;

	public boolean extractSecuritySigntaure(String line) {
	    String[] elements = line.split("\\{");
	    if (extractMethodSignature(elements[0]))
		try {
		    isStatic = line.trim().startsWith("static ");
		    extractSecstubs(elements[1].split("\\}")[0].replaceAll("\\{", "").replaceAll("\\}", ""));
		} catch (StringIndexOutOfBoundsException | java.lang.ArrayIndexOutOfBoundsException ex) {
		    Utils.log(this.getClass(),
			    "This line of  secsum file does not follow a correct method signature: \n 		"
				    + line);
		    return false;
		}
	    return true;
	}

	private void extractSecstubs(String signature) {
	    Matcher m = Pattern.compile("[^;]*;").matcher(signature + ";");
	    while (m.find()) {
		String stub = m.group().trim();
		stub = stub.replaceAll(";", "").trim();
		if (isStatic && stub.contains(".*")) {
		    Utils.logErr(getClass(), className + ":" + method
			    + " is static but its security siganture returns/uses .*. Replaced with return *.");
		    stub = stub.replaceAll("\\.\\*", "\\*");
		}
		if (!stub.equals("") && !secSignature.contains(stub))
		    secSignature.add(stub);
	    }
	}

	String secstubsToString() {
	    String res = "";
	    for (String tmp : this.secSignature)
		res += tmp + ";";
	    return res;
	}

	public boolean extractMethodSignature(String signature) {

	    Matcher m = Pattern.compile("\\S+:\\S+\\s*\\(").matcher(signature);
	    try {
		if (m.find()) {
		    String packAndMethodName = m.group().substring(0, m.group().length() - 1);
		    className = packAndMethodName.split(":")[0].trim();
		    method = packAndMethodName.split(":")[1].trim();
		} else {
		    className = signature.substring(0, signature.indexOf('('));
		    String[] classNameX = className.split(" ");
		    className = classNameX[classNameX.length - 1].trim();
		    method = "";
		}

		m = Pattern.compile("\\(.*\\)").matcher(signature);
		if (m.find()) {
		    String tmp = m.group();
		    tmp = tmp.substring(1, tmp.length() - 1);
		    if (!tmp.equals(""))
			argsType = tmp.replaceAll(" ", "").split(",");
		}

		if (signature.contains(":")) {
		    m = Pattern.compile("(\\S)*\\s*").matcher(signature.replaceAll("static ", "").trim());
		    if (m.find())
			returnType = m.group().trim();
		}
	    } catch (StringIndexOutOfBoundsException ex) {
		Utils.log(this.getClass(),
			"This line of secsum file does not follow a correct method signature: \n 		"
				+ signature);
		return false;
	    } catch (java.lang.ArrayIndexOutOfBoundsException ex) {
		Utils.log(this.getClass(),
			" This line of secsum file does not follow a correct method signature: \n 		"
				+ signature);
		return false;

	    }
	    return true;
	}

	public boolean matches(SootMethod method2) {
	    if (method2.getParameterCount() != argsType.length)
		return false;
	    TypeProcessor typeProcessor = new TypeProcessor(configurations.typeHandlingConfig);
	    try {
		if (!(method2.getDeclaringClass().toString().equals(className) || typeProcessor
			.isSubTypeSuperType(method2.getDeclaringClass(), Scene.v().getSootClass(className)))) {
		    return false;
		}
		if (argsType != null)
		    for (int i = 0; i < argsType.length; i++)
			if (!(argsType[i].equals(method2.getParameterType(i).toString()) || typeProcessor
				.isSubTypeSuperType(Scene.v().getSootClass(method2.getParameterType(i).toString()),
					Scene.v().getSootClass(argsType[i])))) {
			    return false;
			}
		if (returnType != null && (!(this.returnType.equals(method2.getReturnType().toString())
			|| typeProcessor.isSubTypeSuperType(Scene.v().getSootClass(method2.getReturnType().toString()),
				Scene.v().getSootClass(returnType))))) {
		    return false;
		}
		if (returnType == null && !method2.isConstructor()) {
		    return false;
		}
	    } catch (TransformationException e) {
		Utils.log(getClass(),
			"Warning: Runtime error with checking the inheritance relations while checking security signatures ");
		return false;
	    }
	    return true;
	}

	public String header() {
	    String argsTypesDesc = "", separator = "";
	    if (argsType != null)
		for (String arg : argsType) {
		    argsTypesDesc += separator + arg;
		    separator = ",";
		}

	    return (isStatic ? "static " : "") + (returnType != null ? returnType + " " : "")
		    + (className + (("".equals(method)) ? "" : (":" + method))) + "(" + argsTypesDesc + ")";
	}

	@Override
	public String toString() {
	    return this.header() + "{" + secstubsToString() + "}\n";
	}
    }

    public static String escapeTypeName(String type) {
	return type.toString().replaceAll("-", "").replaceAll("-", "").replace(".checkpoint ", ".ccheckpoint ")
		.replace(".checkpoint.", ".ccheckpoint.");
    }

    public static String escapeTypeName(Type type) {
	return type.toString().replaceAll("-", "").replace(".checkpoint ", ".ccheckpoint ").replace(".checkpoint.",
		".ccheckpoint.");

    }

    public ProjectHelper(Configuration settings1) {
	configurations = settings1;
    }

    public ProjectHelper() {
	// TODO Auto-generated constructor stub
    }

    public void analyzeEntryPoints() throws TransformationException {
	TypeProcessor typeProcessor = new TypeProcessor(configurations.typeHandlingConfig);
	for (SootMethod entryPoint : Scene.v().getEntryPoints())
	    analyzeSingleEntrypoint(SootUtilities.getClassName(entryPoint.getDeclaringClass()), entryPoint,
		    typeProcessor, sourceSinkHelper);
	typeProcessor.writeTypesClassesFile(configurations.targetDir);
	// typeProcessor.writeTypeHierarchyDotFile(configurations.outputPath);
    }

    public void analyzeSingleEntrypoint(String className, SootMethod entryPoint, TypeProcessor typeProcessor,
	    SourceSinkHelper sourceSinkHelper) throws TransformationException {
	MethodsHelper syrsHelper = new MethodsHelper(this, configurations, typeProcessor, sourceSinkHelper);
	syrsHelper.processMethod(entryPoint, SootUtilities.getClassName(entryPoint.getDeclaringClass()));
	generateOutputFiles(syrsHelper);
	// return syrsHelper.typeProcessor;
    }

    public boolean constructSymmariesInputFromAPKFiles(String apkFile) {
	try {
	    if (configurations.generateJimple)
		Utils.remakeDirectory(configurations.targetDir + java.io.File.separator + "Jimple");
	    if (configurations.generateCfg)
		Utils.remakeDirectory(configurations.targetDir + java.io.File.separator + "CFG");
	    Utils.remakeDirectory(configurations.targetDir + java.io.File.separator + "Meth");
	    Utils.log(this.getClass(), "Soot: Loading " + apkFile);
	    SootInit.initSootForApk(configurations.extraClassPaths, apkFile, configurations.xmlSourcesAndSinks,
		    configurations.callbacks);
	    analyzeEntryPoints();
	    return true;
	} catch (IOException e) {
	    Utils.logErr(getClass(), "Could not create a dirctory in " + configurations.targetDir);
	    // e.printStackTrace();
	} catch (XmlPullParserException e) {
	    Utils.logErr(getClass(), "Ill-formatted xml file ");
	    // e.printStackTrace();
	} catch (TransformationException e) {
	    Utils.logErr(getClass(), "Aborted Processing the Application due to " + e.getLocalizedMessage());
	}
	return false;
    }

    public String escapeMethodName(String name) {
	return name.replaceAll("<", "").replaceAll(">", "").replaceAll("-", "");
    }

    // public String getUniqueName(MethodInvocation methodInvocation) {

    // return
    // methodInvocation.resolveMethodBinding().getDeclaringClass().getQualifiedName()
    // + methodInvocation.getName();
    // }

    public void extractSinkAndSources() {
	/*
	 * if(configurations.sourcesAndSinks==null) { Utils.log(getClass(),
	 * "The source/sink file (in text format) is missing."); return; }
	 * 
	 * File file = new File(configurations.sourcesAndSinks); if(!file.exists()){
	 * Utils.log(getClass(), "The source/sink file (in text format) " +
	 * configurations.sourcesAndSinks + " does not exist!"); return; }
	 * BufferedReader br; try { br = new BufferedReader(new FileReader(file));
	 * String line = br.readLine(); while (line != null) { String[] elements =
	 * line.split("->"); if (!line.equals("")) { String methodPackageName =
	 * elements[0].split(":")[0].replaceAll("<", "") + "_" +
	 * elements[0].split(":")[1].trim().split(" ")[1]; methodPackageName =
	 * methodPackageName.substring(0, methodPackageName.indexOf("(")); //
	 * java.net.URLConnection: java.io.InputStream getInputStream() if
	 * (elements[1].contains("SINK"))
	 * sourceSinkHelper.sinkMethods.add(methodPackageName); else
	 * sourceSinkHelper.sourceMethods.add(methodPackageName); //
	 * Utils.log(this.getClass(),methodPackageName.trim()); } line = br.readLine();
	 * } } catch (IOException e) { Utils.logErr(this.getClass(),
	 * "Couldn't find the file " + file.getAbsolutePath()); }
	 */
    }

    private void generateOutputFiles(MethodsHelper syrsHelper) throws TransformationException {
	writeAllMethsFile(syrsHelper);
	writeSecstubsFile(syrsHelper);
	// writeMethodsWithNosecsigs(syrsHelper);
	writeSourcesList(syrsHelper);
	writeJavasecstubs(syrsHelper);
    }

    private void writeJavasecstubs(MethodsHelper syrsHelper) {
	Collections.sort(javaSecstubs);
	String output = "";
	for (String secstub : javaSecstubs)
	    output += secstub;

	Utils.writeTextFile(configurations.targetDir + "JavaSecstubs.txt", output);

    }

    private void writeAllMethsFile(MethodsHelper syrsHelper) {
	String meth_files = "";
	String targetDir = Utils.polishFilePath(configurations.targetDir// .replaceAll(BenchmarkExperimentConfig.outputFolderPath,
	// "")
	);
	for (String method : syrsHelper.processedMethods)
	    if (!configurations.excludedMathods.contains(method)) { // && !method.contains("dummyMainMethod"))
		meth_files += Utils.polishFilePath(targetDir + "/Meth/" + method + ".meth\n");
		// meth_files += Utils.polishFilePath( "/home/ubuntu/SyrsWorks/" + new
		// File(targetDir).getName() + "/Meth/" + method + ".meth\n");

		// Utils.log(this.getClass(),"Exported the file " + "/Meth/" + method +
		// ".meth");
	    }
	Utils.writeTextFile(configurations.targetDir + "/Meth/all.meth_files", meth_files);
	// Utils.log(this.getClass(), "Created the file /Meth/all.meth_files");
    }

    private void writeSourcesList(MethodsHelper syrsHelper) {
	String sourcesList = "";
	for (SootMethod method : Scene.v().getEntryPoints()) {
	    sourcesList += getMethodUniqueName(method, method.getDeclaringClass().getName()) + "\n";
	}
	Utils.writeTextFile(configurations.targetDir + "/Meth/all." + Constants.srcsExtension, sourcesList);
    }

    private void writeMethodsWithNosecsigs(MethodsHelper syrsHelper) throws TransformationException {
	String temp = Utils.readStringTextFile(configurations.targetDir + "/Misc/autoGeneratedSecsigs.txt") + "\n";
	this.methodsWithAutoGeneratedSecSignature.sort(new SootMethodsComparator());
	for (SootMethod method : methodsWithAutoGeneratedSecSignature) {
	    String assumption = syrsHelper.constructHeader(method, true,
		    SootUtilities.getClassName(method.getDeclaringClass()), new ArrayList<Value>());
	    assumption += "{" + getAutoGenLibSecstubs().get(method) + "}\n";
	    if (!temp.contains(assumption)) {
		temp += assumption + "\n";
		// this.librarySecurityAssumptions.get().
	    }
	}
	Utils.writeTextFile(this.configurations.targetDir + "/Misc/autoGeneratedSecsigs.txt", temp);

	temp = Utils.readStringTextFile(this.configurations.targetDir + "/Misc/noSecsigs.txt") + "\n";
	methodsWithNoSecSignature.sort(new SootMethodsComparator());
	for (SootMethod method : methodsWithNoSecSignature) {
	    String assumption = syrsHelper.constructHeader(method, true,
		    SootUtilities.getClassName(method.getDeclaringClass()), new ArrayList<Value>());
	    assumption += "{" + getAutoGenLibSecstubs().get(method) + "}\n";
	    if (!temp.contains(assumption)) {
		temp += assumption + "\n";
		// this.librarySecurityAssumptions.get().
	    }
	}
	Utils.writeTextFile(this.configurations.targetDir + "/Misc/noSecsigs.txt", temp);

    }

    private void writeSecstubsFile(MethodsHelper syrsHelper) throws TransformationException {
	String secstubs = "", methodSecstub = "";

	for (ArrayList<SecuritySignature> ssl : securitySignatures.values())
	    for (SecuritySignature ss : ssl) {
		// if (!secstubs.contains(ss.header ()))
		secstubs += ss.toString();
		if (ss.toString().contains(" java.") && !javaSecstubs.contains(ss.toString()))
		    this.javaSecstubs.add(ss.toString());
	    }

	for (SootMethod method : getSortedLibrarySecurityAssumptions()) {
	    String assumption = syrsHelper.constructHeader(method, true,
		    SootUtilities.getClassName(method.getDeclaringClass()), new ArrayList<Value>());
	    methodSecstub = "";
	    if (!secstubs.contains(assumption)) {
		methodSecstub = assumption + "{";
		for (String tmp : getAutoGenLibSecstubs().get(method))
		    methodSecstub += tmp + ";";
		methodSecstub += "}\n";
	    }
	    secstubs += methodSecstub;
	    if (method.getDeclaringClass().getName().contains("java.") && !javaSecstubs.contains(methodSecstub))
		this.javaSecstubs.add(methodSecstub);

	}

	for (Type type : syrsHelper.dummyLowSinkMethodsList)
	    secstubs += "static void " + Constants.dummyClass + ":" + Constants.lowSinkMethodName + "(" + type
		    + "){-<~; output_⊥;}\n";
	for (Type type : syrsHelper.dummyHighSinkMethodsList)
	    secstubs += "static void " + Constants.dummyClass + ":" + Constants.highSinkMethodName + "(" + type
		    + "){-<~; @!;}\n";
	for (Type type : syrsHelper.dummyLowSourceMethodsList)
	    secstubs += "static " + type + " " + Constants.dummyClass + ":" + Constants.lowSourceMethodName
		    + "(){ -<~; return new_?}\n";
	for (Type type : syrsHelper.dummyHighSourceMethodsList)
	    // secstubs += "static " + type + " " + Constants.dummyClass + ":" +
	    // Constants.highSourceMethodName
	    // + "(){ -<~; return new(%(*))}\n";
	    secstubs += "static void " +
	    // Constants.dummyClass + ":" + Constants.highSourceMethodName +
		    SourceSinkHelper.dummyHighSourceMethodNameForSig(type) + "(" + type + "){-<~; @<~%(*)}\n";
	for (TypeCaster typeCaster : syrsHelper.dummyTypeCastMethodsList)
	    secstubs += "static " + typeCaster.type2 + " " + Constants.dummyClass + ":" + typeCaster.getMethodName()
		    + "(" + typeCaster.type1 + " " + "){-<~;return *}\n";
	Utils.writeTextFile(
		configurations.targetDir + java.io.File.separator + "Meth" + java.io.File.separator + "all.secstubs",
		secstubs);
    }

    public String getMethodUniqueName(SootMethod method, String declaringClass) {
	return (method.isConstructor() ? declaringClass : // SootUtilities.getClassName(method.getDeclaringClass()):
		declaringClass + // SootUtilities.getClassName(method.getDeclaringClass()) +
		// //(method.isConstructor()?"":
			"_" + escapeMethodName(method.getName()) + method.equivHashCode())
		.replaceAll("-", "");
    }

    public String getMethodUniqueNameV2(SootMethod method) {
	return SootUtilities.getClassName(method.getDeclaringClass()) + // (method.isConstructor()?"":
		"_" + escapeMethodName(method.getName());
    }

    static String polishVarName(Value value) {
	String v = value.toString();
	switch (v) {
	case "neg":
	case "cmp":
	case "cmpl":
	case "cmpg":
	case "checkpoint":
	case "monitorenter":
	case "output_t":
	case "output_T":
	case "output_l":
	case "output_L":
	case "exit":
	    return v + "$$";
	default:
	    return v;
	}
    }

    static String polishConstantName(Value value) {
	String v = value.toString();
	switch (v) {
	case "Infinity":
	case "NaN":
	    return (value.getType().toString().equals("java.lang.String") ? "\"0\"" : "0");
	default:
	    return v;
	}
    }

    static String polishFieldName(String value) {
	if (value.equals("checkpoint"))
	    return "f" + value;
	return value;
    }

    static String polishClassName(String value) {
	return value.replace(".checkpoint ", ".ccheckpoint ").replace(".checkpoint.", ".ccheckpoint.");
    }

    public void loadAssumedSecuritySignatures() {
	if (configurations.sigsecsfiles == null || configurations.sigsecsfiles.length == 0) {
	    Utils.log(getClass(), "The security stubs file is missing.");
	    return;
	}
	for (String fileName : configurations.sigsecsfiles) {
	    File file = new File(fileName);
	    if (!file.exists()) {
		Utils.log(getClass(), "The security stubs file " + file.getAbsolutePath() + " does not exist.");
		continue;
	    }
	    Utils.log(getClass(), "Loading security stubs file " + file.getAbsolutePath());
	    BufferedReader br;
	    try {
		br = new BufferedReader(new FileReader(file));
		String line = br.readLine();
		while (line != null) {
		    String l = line.trim();
		    if (!l.equals("") && !l.startsWith("//")) {
			SecuritySignature securitySignature = new SecuritySignature();
			if (securitySignature.extractSecuritySigntaure(l)) {
			    if (securitySignatures.get(securitySignature.method) == null)
				securitySignatures.put(securitySignature.method, new ArrayList<SecuritySignature>());
			    securitySignatures.get(securitySignature.method).add(securitySignature);
			}
		    }
		    line = br.readLine();
		}
	    } catch (IOException e) {
		Utils.logErr(this.getClass(), "Couldn't find the file " + file.getAbsolutePath());
	    }
	}
    }

    public LinkedHashMap<SootMethod, ArrayList<String>> getAutoGenLibSecstubs() {
	return autoGenLibSecstubs;
    }

    public class SootMethodsComparator implements Comparator {
	@Override
	public int compare(Object o1, Object o2) {
	    if (((SootMethod) o1).isJavaLibraryMethod() && !((SootMethod) o2).isJavaLibraryMethod())
		return 1;
	    else if (((SootMethod) o2).isJavaLibraryMethod() && !((SootMethod) o1).isJavaLibraryMethod())
		return -1;
	    else
		return (((SootMethod) o1).getDeclaringClass().getName() + ((SootMethod) o1).getName())
			.compareTo(((SootMethod) o2).getDeclaringClass().getName() + ((SootMethod) o2).getName());
	}
    }

    public List<SootMethod> getSortedLibrarySecurityAssumptions() {
	List<SootMethod> sortedKeys = new ArrayList<SootMethod>();
	sortedKeys.addAll(autoGenLibSecstubs.keySet());
	Collections.sort(sortedKeys, new SootMethodsComparator());
	return sortedKeys;
    }

    public void setLibrarySecurityAssumptions(LinkedHashMap<SootMethod, ArrayList<String>> librarySecurityAssumptions) {
	this.autoGenLibSecstubs = librarySecurityAssumptions;
    }

    public void extractSourceSinkFromXML() {
	sourceSinkHelper = new SourceSinkHelper();
	XMLSourceSinkParser xmlParser = new XMLSourceSinkParser();
	if (xmlParser.readXMLFile(configurations.xmlSourcesAndSinks)) {
	    Utils.log(getClass(), "Processing the xml file " + configurations.xmlSourcesAndSinks);
	    xmlParser.getAllSinksOrSources(sourceSinkHelper.highSources, true, true);
	    xmlParser.getAllSinksOrSources(sourceSinkHelper.highSinks, true, false);
	    xmlParser.getAllSinksOrSources(sourceSinkHelper.lowSources, false, true);
	    xmlParser.getAllSinksOrSources(sourceSinkHelper.lowSinks, false, false);
	}
	if (sourceSinkHelper.highSources.isEmpty())
	    Utils.log(getClass(), "The application has NO high source!");
	if (sourceSinkHelper.lowSources.isEmpty())
	    Utils.log(getClass(), "The application has NO low source!");
	if (sourceSinkHelper.highSinks.isEmpty())
	    Utils.log(getClass(), "The application has NO high sink!");
	if (sourceSinkHelper.lowSinks.isEmpty())
	    Utils.log(getClass(), "The application has NO low sink!");
    }

    public void loadSecstubsFromXMLFile() {
	XMLSecstubsParser xmlParser = new XMLSecstubsParser();
	if (xmlParser.readXMLFile(configurations.xmlSecsstubsPath)) {
	    xmlParser.getSecstubs(securitySignatures);
	}
    }

    /*
     *
     * secstubs += "void " + Constants.dummyClass + ":" +
     * Constants.lowSinkMethodName + "(" + type + "){output_⊥;}\n"; for (Type type :
     * syrsHelper.dummyHighSinkMethodsList) secstubs += "void " +
     * Constants.dummyClass + ":" + Constants.highSinkMethodName + "(" + type +
     * "){@!;}\n"; for (Type type : syrsHelper.dummyLowSourceMethodsList) secstubs
     * += type + " " + Constants.dummyClass + ":" + Constants.lowSourceMethodName +
     * "(){ -<~; return new_?}\n"; for (Type type :
     * syrsHelper.dummyHighSourceMethodsList) secstubs += type + " " +
     * Constants.dummyClass + ":" + Constants.highSourceMethodName +
     * "(){ -<~; return .*h }\n";
     * 
     */

    public void extractSourceSinksFromSecuritySignatures() {
	if (this.sourceSinkHelper.lowSinks.get(Utils.XMlMethod) == null)
	    this.sourceSinkHelper.lowSinks.put((String) Utils.XMlMethod, new ArrayList());
	if (this.sourceSinkHelper.lowSinks.get(Utils.XMLReference) == null)
	    this.sourceSinkHelper.lowSinks.put((String) Utils.XMLReference, new ArrayList());
	if (this.sourceSinkHelper.highSinks.get(Utils.XMLReference) == null)
	    this.sourceSinkHelper.highSinks.put((String) Utils.XMLReference, new ArrayList());
	if (this.sourceSinkHelper.highSinks.get(Utils.XMlMethod) == null)
	    this.sourceSinkHelper.highSinks.put((String) Utils.XMlMethod, new ArrayList());
	if (this.sourceSinkHelper.lowSources.get(Utils.XMlMethod) == null)
	    this.sourceSinkHelper.lowSources.put((String) Utils.XMlMethod, new ArrayList());
	if (this.sourceSinkHelper.highSources.get(Utils.XMlMethod) == null)
	    this.sourceSinkHelper.highSources.put((String) Utils.XMlMethod, new ArrayList());
	for (String method : this.securitySignatures.keySet()) {
	    List<SecuritySignature> signatures = securitySignatures.get(method);
	    for (SecuritySignature sig : signatures) {
		if (sig.secSignature.contains("return .*h") || sig.secSignature.contains("return *h")
			|| sig.secSignature.contains("return new(%(*))")) {
		    this.sourceSinkHelper.highSources.get(Utils.XMlMethod)
			    .add(new String[] { "L" + sig.className.replaceAll("\\.", "/"), sig.method });
		    Utils.log(getClass(), "Added " + sig.className + "." + sig.method + " as a HIGH source.");
		}

		if (sig.secSignature.contains("output_l")) {
		    if (sig.argsType.length > 0)
			this.sourceSinkHelper.lowSinks.get(Utils.XMlMethod)
				.add(new String[] { "L" + sig.className.replaceAll("\\.", "/"), sig.method });
		    else
			this.sourceSinkHelper.lowSinks.get(Utils.XMLReference)
				.add(new String[] { "L" + sig.className.replaceAll("\\.", "/"), sig.method });
		    Utils.log(getClass(), "Added " + sig.className + "." + sig.method + " as a LOW sink.");
		}

		if (sig.secSignature.contains("@!")) {
		    if (sig.argsType.length > 0)
			this.sourceSinkHelper.highSinks.get(Utils.XMlMethod)
				.add(new String[] { "L" + sig.className.replaceAll("\\.", "/"), sig.method });
		    else
			this.sourceSinkHelper.highSinks.get(Utils.XMLReference)
				.add(new String[] { "L" + sig.className.replaceAll("\\.", "/"), sig.method });
		    Utils.log(getClass(), "Added " + sig.className + "." + sig.method + " as a HIGH sink.");
		}

		if (sig.secSignature.contains("return new_?")) {
		    this.sourceSinkHelper.lowSources.get(Utils.XMlMethod)
			    .add(new String[] { "L" + sig.className.replaceAll("\\.", "/"), sig.method });
		    Utils.log(getClass(), "Added " + sig.className + "." + sig.method + " as a LOW source.");
		}

	    }
	}
    }

    /**
     * Load each class, iterate its methods, print signature + Jimple body (if
     * concrete).
     * 
     * @param symmariesHelper
     */
    private void processClasses(List<String> classNames, MethodsHelper symmariesHelper)
	    throws TypeTransformationException {
	// Pre-load a few core classes to stabilize Scene
	Scene.v().loadClassAndSupport("java.lang.Object");
	Scene.v().loadNecessaryClasses();

	for (String clsName : classNames) {
	    try {
		SootClass sootClass = Scene.v().loadClassAndSupport(clsName);
		// mark as application so Soot bothers materializing bodies where possible
		sootClass.setApplicationClass();
		Scene.v().loadNecessaryClasses();

		System.out.println();
		System.out.println("==================== CLASS: " + sootClass.getName() + " ====================");

		for (SootMethod m : sootClass.getMethods()) {
		    System.out.println();
		    System.out.println("---- Analyzing Method: " + m.getSignature() + " ----");
		    if (!symmariesHelper.processedMethods.contains(getMethodUniqueName(m, sootClass.getName()))) {
			symmariesHelper.processMethod(m, SootUtilities.getClassName(m.getDeclaringClass()));
		    }
		}

	    } catch (Exception e) {
		System.err.println("[error] Failed to load class " + clsName + ": " + e);
	    }
	}

    }

    public void processApplication(List<String> allClasses) {
	MethodsHelper symmariesHelper = new MethodsHelper(this, configurations,
		new TypeProcessor(configurations.typeHandlingConfig), sourceSinkHelper);
	try {
	    processClasses(allClasses, symmariesHelper);
	    generateOutputFiles(symmariesHelper);
	    symmariesHelper.typeProcessor.writeTypesClassesFile(configurations.targetDir);
	    // symmariesHelper.typeProcessor.writeTypeHierarchyDotFile(configurations.outputPath);
	} catch (TransformationException | TypeTransformationException e) {
	    Utils.logErr(JSymCompiler.class, "Aborted Processing the Application due to " + e.getLocalizedMessage());
	}

    }

    public void clear() {
	// this.autoGenLibSecstubs.clear();
	this.methodsWithAutoGeneratedSecSignature.clear();
	this.methodsWithNoSecSignature.clear();
	this.securitySignatures.clear();
	this.sourceSinkHelper.highSinks.clear();
	this.sourceSinkHelper.lowSinks.clear();
	this.sourceSinkHelper.highSources.clear();
	this.sourceSinkHelper.lowSources.clear();
	this.staticFileds = "";
    }
}
